name: Test

on:
  pull_request_target:
    branches: [master]

jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Make CLI version
        run: |
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build -S .
          cmake --build build
          cmake --build build --target install

      - name: Download latest GCLC release
        run: |
          mkdir latest
          cd latest
          wget https://github.com/janicicpredrag/gclc/releases/latest/download/linux.zip
          unzip linux.zip gclc
          chmod +x gclc

      - name: Run tests
        run: |
          ./test/compare_outputs.sh executable/gclc latest/gclc ./samples/basic_samples/
          echo '## Basic samples' >> $GITHUB_STEP_SUMMARY
          cat diff-log >> $GITHUB_STEP_SUMMARY
          ./test/compare_proofs.sh executable/gclc latest/gclc ./samples/samples_prover/
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '## Prover samples' >> $GITHUB_STEP_SUMMARY
          cat proof-log >> $GITHUB_STEP_SUMMARY
